errorPath: /error

server:
  port: 8081
  servlet:
    context-path: /
  error:
    path: error_path
  ssl:
    key-store: file:${KEYSTORE_FILE:}
    key-store-password: ${KEYSTORE_PASSWORD:}
    enabled: ${SSL_ENABLED:false}

spring:
  profiles:
    active: Logging
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/books}
    username: ${DATASOURCE_USERNAME:japp}
    password: ${DATASOURCE_PASSWORD:secret}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 10
      register-mbeans: true
  jpa:
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}
        format_sql: true
        id:
          new_generator_mappings: false
  liquibase:
    user: ${DATASOURCE_ADMIN_USERNAME:jadmin}
    password: ${DATASOURCE_ADMIN_PASSWORD:moresecret}
    change-log: classpath:changelog/db.changelog.sql
