errorPath: /error

server:
  port: 8081
  servlet:
    context-path: /
  error:
    path: error_path
  ssl:
    key-store: "file:./docker/certs/localhost-keystore.jks"
    key-store-password: mypass
    enabled: true

spring:
  profiles:
    active: Logging
  security:
    user:
      name: user
      password: password
  datasource:
    url: jdbc:mysql://localhost:3306/books?verifyServerCertificate=true&useSSL=true&requireSSL=true&clientCertificateKeyStoreUrl=file:./docker/certs/localhost-keystore.jks&clientCertificateKeyStorePassword=mypass&trustCertificateKeyStoreUrl=file:./docker/certs/truststore.ts&trustCertificateKeyStorePassword=mypass
    username: japp
    password: secret
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 10
      register-mbeans: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        id:
          new_generator_mappings: false

endpoints:
  jmx:
    enabled: true
