version: "3"
services:
  books-mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: strong_pwd
    volumes:
      - books-mysql-data:/var/lib/mysql
      - "./data:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"

  books-myadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    environment:
      - PMA_HOST=books-mysql
      - PMA_USER=root
      - PMA_PASSWORD=strong_pwd
    ports:
      - "8080:80"

  books-api:
    image: francescofiora-book
    environment:
      - DATASOURCE_URL=jdbc:mysql://books-mysql:3306/books
    ports:
      - "8081:8081"
    depends_on:
      - books-mysql

volumes:
  books-mysql-data:
