version: "3"
services:
  books-mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: strong_pwd
    volumes:
      - books-mysql-data:/var/lib/mysql
      - "./conf.d:/etc/mysql/conf.d/"
      - "./certs:/etc/certs"
      - "./data:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"

  books-myadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    environment:
      - PMA_HOST=books-mysql
      - PMA_USER=root
      - PMA_PASSWORD=strong_pwd
    volumes:
      - "./certs:/etc/certs"
      - "./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php"
    ports:
      - "8080:80"

volumes:
  books-mysql-data:
