services:
  books-mysql:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: strong_pwd
    volumes:
      - books-mysql-data:/var/lib/mysql
      - "./data:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"

  books-myadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    environment:
      - PMA_HOST=books-mysql
      - PMA_USER=root
      - PMA_PASSWORD=strong_pwd
    ports:
      - "8080:80"

volumes:
  books-mysql-data:
